name: Build & Deploy LibreChat

on:
  push:
    branches: [main]

permissions:
  id-token: write
  contents: read
  packages: write

env:
  ACR_NAME: kaleidoscopeaieducation             # can change if container repo changes in azure
  ACR_LOGIN: kaleidoscopeaieducation-ajfgb4ceepedbyc5.azurecr.io
  RG_CORE:  main-container-repo
  BICEP_FILE: infra/main.bicep
  APP_IMAGE: libreclient

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      # 1. Login to Azure via OIDC
      - name: Azure Login (OIDC)
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      # 2. ACR login (token comes from az CLI session)
      - name: ACR login
        run: az acr login --name $ACR_NAME

      # 3. Build & push the Docker image
      - name: Build & Push image
        run: |
          docker build -t $ACR_LOGIN/$APP_IMAGE:${{ github.sha }} .
          docker push $ACR_LOGIN/$APP_IMAGE:${{ github.sha }}

      # 4. Deploy / update ACA via Bicep
      - name: Bicep deploy
        run: |
          az deployment group create \
            --resource-group $RG_CORE \
            --template-file $BICEP_FILE \
            --parameters imageTag=${{ github.sha }} \
                         imageRepo=$ACR_LOGIN/$APP_IMAGE
