name: Build & Deploy LibreChat

on:
  push:
    branches: [main]

permissions:
  id-token: write
  contents: read
  packages: write

env:
  ACR_NAME: kaleidoscopeaieducation             # can change if container repo changes in azure
  ACR_LOGIN: kaleidoscopeaieducation-ajfgb4ceepedbyc5.azurecr.io
  RG_CORE:  main-container-repo
  BICEP_FILE: infra/main.bicep
  APP_IMAGE: libreclient

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      # 1. Login to Azure via OIDC
      - name: Azure Login (OIDC)
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      # 2. ACR login (token comes from az CLI session)

      - name: Downgrade Azure CLI (work-around for #31581)
        run: |
          sudo apt-get update -y
          sudo apt-get install --yes azure-cli=2.72.0-1~$(lsb_release -cs)
          az --version   # confirm
      - name: ACR login
        run: az acr login --name $ACR_NAME

      # 3. Build & push the Docker image
      - name: Build & Push image
        run: |
          docker build -t $ACR_LOGIN/$APP_IMAGE:${{ github.sha }} .
          docker push $ACR_LOGIN/$APP_IMAGE:${{ github.sha }}

      # ── 5. Build parameter file for the Bicep deploy ─────────
      - name: Build parameter file
        run: |
          cat > deploy-params.json <<EOF
          {
            "acrName":      { "value": "$ACR_NAME" },
            "imageRepo":    { "value": "$ACR_LOGIN/$APP_IMAGE" },
            "imageTag":     { "value": "${{ github.sha }}" },
            "mongoUri":     { "value": "${{ secrets.MONGO_URI }}" },
            "openaiApiKey": { "value": "${{ secrets.OPENAI_API_KEY }}" }
          }
          EOF

      # ── 6. Deploy / update ACA via Bicep ─────────────────────
      - name: Deploy to ACA via Bicep
        run: |
          az deployment group create \
            --resource-group "$RG_CORE" \
            --template-file "$BICEP_FILE" \
            --parameters @deploy-params.json